// Word segmentation backed by the ChiaKey Lexicon.
//
// The dictionary is generated by scripts/generateChatLexicon.js from the same
// NAER frequency table and modern overlays the input method ships, so the
// terminal knows exactly the vocabulary ChiaKey knows.

export type Token = {
  text: string
  /** Present in the dictionary rather than fallen back to per-character. */
  known: boolean
  /** Contributed by the modern overlays — post-war vocabulary, in-world. */
  modern: boolean
}

export type Lexicon = {
  /** word → log10 probability, already divided by the per-million total. */
  weights: Map<string, number>
  modern: Set<string>
  maxWordLength: number
}

const BUCKETS = 64
const WEIGHT_BASE = 48
const MIN_LOG = Math.log10(0.3)
const MAX_LOG = Math.log10(60000)
const PER_MILLION = 6 // log10(1e6)

// Slightly rarer than the rarest dictionary entry, so any real word beats the
// per-character fallback, but a stray character still costs a bounded amount.
const UNKNOWN_LOG_PROBABILITY = MIN_LOG - 0.6 - PER_MILLION

export const parseLexicon = (source: string): Lexicon => {
  const weights = new Map<string, number>()
  const modern = new Set<string>()
  let maxWordLength = 1
  let previous = ''

  for (const line of source.split('\n')) {
    if (!line) continue
    let body = line
    let isModern = false
    if (body.endsWith('*')) {
      isModern = true
      body = body.slice(0, -1)
    }
    const bucket = body.charCodeAt(body.length - 1) - WEIGHT_BASE
    const shared = body.charCodeAt(0) - 48
    const word = previous.slice(0, shared) + body.slice(1, -1)
    previous = word

    const frequency = 10 ** (MIN_LOG + (bucket / (BUCKETS - 1)) * (MAX_LOG - MIN_LOG))
    weights.set(word, Math.log10(frequency) - PER_MILLION)
    if (isModern) modern.add(word)
    if (word.length > maxWordLength) maxWordLength = word.length
  }

  return { weights, modern, maxWordLength }
}

const CJK = /[㐀-䶿一-鿿豈-﫿]/

/**
 * Maximum-probability segmentation over the word DAG — the same shape as
 * jieba's, minus the HMM pass for unknown words. Runs backwards so each
 * position only needs the already-solved suffix.
 */
export const segment = (text: string, lexicon: Lexicon | null): Token[] => {
  if (!text) return []
  if (!lexicon) return [{ text, known: false, modern: false }]

  const { weights, maxWordLength } = lexicon
  const length = text.length
  // route[i] = best total log-probability for text.slice(i), and the end index
  // of the word chosen at i.
  const score = new Float64Array(length + 1)
  const jump = new Int32Array(length + 1)

  for (let i = length - 1; i >= 0; i -= 1) {
    let best = -Infinity
    let bestEnd = i + 1
    const limit = Math.min(length, i + maxWordLength)
    for (let end = i + 1; end <= limit; end += 1) {
      const candidate = text.slice(i, end)
      const weight = weights.get(candidate)
      if (weight === undefined) {
        // Only the single-character fallback survives an unknown slice; longer
        // unknown slices are always beaten by splitting them.
        if (end > i + 1) continue
        const total = UNKNOWN_LOG_PROBABILITY + score[end]
        if (total > best) {
          best = total
          bestEnd = end
        }
        continue
      }
      const total = weight + score[end]
      if (total > best) {
        best = total
        bestEnd = end
      }
    }
    score[i] = best
    jump[i] = bestEnd
  }

  const tokens: Token[] = []
  for (let i = 0; i < length; i = jump[i]) {
    const word = text.slice(i, jump[i])
    tokens.push({
      text: word,
      known: weights.has(word),
      modern: lexicon.modern.has(word),
    })
  }
  return tokens
}

/** Splits on anything the segmenter shouldn't run over, keeping latin runs whole. */
export const segmentAll = (text: string, lexicon: Lexicon | null): Token[] => {
  const tokens: Token[] = []
  let buffer = ''

  const flush = () => {
    if (!buffer) return
    tokens.push(...segment(buffer, lexicon))
    buffer = ''
  }

  let latin = ''
  const flushLatin = () => {
    if (!latin) return
    tokens.push({ text: latin, known: false, modern: false })
    latin = ''
  }

  for (const char of text) {
    if (CJK.test(char)) {
      flushLatin()
      buffer += char
    } else if (/[0-9a-z]/i.test(char)) {
      flush()
      latin += char
    } else {
      flush()
      flushLatin()
      if (char.trim()) tokens.push({ text: char, known: false, modern: false })
    }
  }
  flush()
  flushLatin()
  return tokens
}

let pending: Promise<Lexicon> | null = null

export const loadLexicon = (): Promise<Lexicon> => {
  if (!pending) {
    pending = fetch('/assets/story/terminal/lexicon.txt')
      .then((response) => {
        if (!response.ok) throw new Error(`lexicon ${response.status}`)
        return response.text()
      })
      .then(parseLexicon)
      .catch((error) => {
        pending = null
        throw error
      })
  }
  return pending
}
