import Head from 'next/head'
import { useRouter } from 'next/router'
import { localizedPath, pagePathFromLocalePath, type Locale, useI18n } from 'i18n'
import { getMainLinks, getNavSections } from 'components/nav/navData'

const SITE_URL = 'https://chiaki.ch'
const SITE_NAME = '千秋稻荷社'

type PageMeta = {
  key: string
  image: string
}

// Per-page SEO overrides supplied through getStaticProps (e.g. individual blog
// posts, whose title/description/image can't live in the static map below).
export type PageMetaOverride = {
  title: string
  description: string
  image: string
  /** External canonical, e.g. a cross-posted article. Suppresses hreflang alternates. */
  canonical?: string
  /** BCP-47 language of the content, defaults to the current UI locale. */
  inLanguage?: string
  /** Clean label for the last breadcrumb crumb (title often carries a site suffix). */
  breadcrumbName?: string
  /** Presence marks the page as an Article (og:type=article + BlogPosting schema). */
  article?: {
    publishedTime: string
    modifiedTime?: string
    tags?: string[]
  }
}

const pageMetadata: Record<string, PageMeta> = {
  '/': { key: 'home', image: '/og/home.jpeg' },
  '/profile': { key: 'profile', image: '/og/profile.jpeg' },
  '/story': { key: 'story', image: '/og/story.jpeg' },
  '/story/character': { key: 'character', image: '/og/story-character.jpeg' },
  '/story/character/art': { key: 'art', image: '/og/story-character-art.jpeg' },
  '/works': { key: 'works', image: '/og/works.jpeg' },
  '/works/chiakey': { key: 'chiakey', image: '/og/works-chiakey.jpeg' },
  '/works/kumiko': { key: 'kumiko', image: '/og/works-kumiko.jpeg' },
  '/works/tg-jpg': { key: 'tgJpg', image: '/og/works-tg-jpg.jpeg' },
  '/works/split-flap': { key: 'splitFlap', image: '/og/works-split-flap.jpeg' },
  '/works/tokyono-sora': { key: 'tokyonoSora', image: '/og/works-tokyono-sora.jpeg' },
  '/fonts': { key: 'fonts', image: '/og/fonts.jpeg' },
  '/fonts/akitra': { key: 'akitra', image: '/og/fonts-akitra.jpeg' },
  '/fonts/nixie': { key: 'nixie', image: '/og/fonts-nixie.jpeg' },
  '/fonts/huninn': { key: 'huninn', image: '/og/fonts-huninn.jpeg' },
  '/blog': { key: 'blog', image: '/og/blog.jpeg' },
}

const fallbackMetadata = pageMetadata['/']

const languageTags: Record<Locale, string> = {
  tw: 'zh-TW',
  ja: 'ja',
  en: 'en',
}

// Extra JSON-LD fields merged into the page node (rich-result eligibility)
const pageSchemaExtras: Record<string, Record<string, unknown>> = {
  '/profile': {
    mainEntity: { '@id': `${SITE_URL}/#chiaki` },
  },
  '/works/chiakey': {
    operatingSystem: 'macOS',
    applicationCategory: 'UtilitiesApplication',
    offers: { '@type': 'Offer', price: 0, priceCurrency: 'TWD' },
    downloadUrl: 'https://cdn.chiaki.ch/chiakey/ChiaKey.pkg',
    isBasedOn: 'https://github.com/YahooArchive/KeyKey',
  },
}

const pageSchemaType: Record<string, string> = {
  '/profile': 'ProfilePage',
  '/blog': 'Blog',
  '/works': 'CollectionPage',
  '/fonts': 'CollectionPage',
  '/works/chiakey': 'SoftwareApplication',
  '/works/kumiko': 'SoftwareApplication',
  '/works/tg-jpg': 'SoftwareSourceCode',
  '/works/split-flap': 'SoftwareSourceCode',
  '/works/tokyono-sora': 'SoftwareSourceCode',
  '/fonts/akitra': 'CreativeWork',
  '/fonts/nixie': 'CreativeWork',
  '/fonts/huninn': 'CreativeWork',
}

const PageMeta = ({ override }: { override?: PageMetaOverride }) => {
  const { asPath } = useRouter()
  const { locale, t } = useI18n()
  const pathname = asPath.split(/[?#]/, 1)[0] || '/'
  const pagePath = pagePathFromLocalePath(pathname)
  const metadata = pageMetadata[pagePath] ?? fallbackMetadata
  const isArticle = !!override?.article
  const title = override?.title ?? t(`meta.${metadata.key}.title`)
  const description = override?.description ?? t(`meta.${metadata.key}.description`)
  const pageUrl = `${SITE_URL}${pathname === '/' ? '' : pathname}`
  const canonicalUrl = override?.canonical ?? pageUrl
  const imageUrl = override?.image
    ? override.image.startsWith('http')
      ? override.image
      : `${SITE_URL}${override.image}`
    : `${SITE_URL}${metadata.image}`
  const inLanguage = override?.inLanguage ?? languageTags[locale]
  const ogType = isArticle ? 'article' : 'website'
  const schemaType = pageSchemaType[pagePath] ?? 'WebPage'
  // Only pages listed in pageMetadata have ja/en versions generated by the
  // [locale] catch-all. Others (e.g. individual blog posts) are single-language,
  // so they must not emit alternate hreflang links pointing at non-existent URLs.
  // A custom canonical (cross-post) also opts out of the multilingual cluster.
  const isLocalized = pagePath in pageMetadata && !override?.canonical

  // Breadcrumb trail derived from the same nav data that drives the SubNav, so
  // structured breadcrumbs stay in sync with the visible navigation.
  const breadcrumbItems = (() => {
    if (pagePath === '/') return [] as { name: string; url: string }[]
    const titleByPath = new Map<string, string>()
    getMainLinks(t).forEach(([label, path]) => titleByPath.set(path, label))
    Object.values(getNavSections(t)).forEach((section) =>
      section.items.forEach((item) => titleByPath.set(item.path, item.title))
    )
    const crumbs = [{ name: SITE_NAME, url: `${SITE_URL}${localizedPath('/', locale)}` }]
    let acc = ''
    const segments = pagePath.split('/').filter(Boolean)
    segments.forEach((segment, index) => {
      acc += `/${segment}`
      const isLast = index === segments.length - 1
      const name =
        titleByPath.get(acc) ?? (isLast ? override?.breadcrumbName ?? title : segment)
      crumbs.push({ name, url: `${SITE_URL}${localizedPath(acc, locale)}` })
    })
    return crumbs
  })()

  const needsPerson = pagePath === '/' || pagePath === '/profile' || isArticle

  const pageNode = isArticle
    ? {
        '@type': 'BlogPosting',
        '@id': `${canonicalUrl}#blogpost`,
        url: canonicalUrl,
        headline: title,
        description,
        image: imageUrl,
        datePublished: override!.article!.publishedTime,
        dateModified: override!.article!.modifiedTime ?? override!.article!.publishedTime,
        inLanguage,
        isPartOf: { '@id': `${SITE_URL}/#website` },
        mainEntityOfPage: canonicalUrl,
        author: { '@id': `${SITE_URL}/#chiaki` },
        publisher: { '@id': `${SITE_URL}/#chiaki` },
        ...(override!.article!.tags?.length
          ? { keywords: override!.article!.tags.join(', ') }
          : {}),
        ...(breadcrumbItems.length
          ? { breadcrumb: { '@id': `${canonicalUrl}#breadcrumb` } }
          : {}),
      }
    : {
        '@type': schemaType,
        '@id': `${canonicalUrl}#webpage`,
        url: canonicalUrl,
        name: title,
        description,
        image: imageUrl,
        inLanguage,
        isPartOf: { '@id': `${SITE_URL}/#website` },
        ...(breadcrumbItems.length
          ? { breadcrumb: { '@id': `${canonicalUrl}#breadcrumb` } }
          : {}),
        ...(pageSchemaExtras[pagePath] ?? {}),
      }

  const structuredData = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'WebSite',
        '@id': `${SITE_URL}/#website`,
        url: SITE_URL,
        name: SITE_NAME,
        inLanguage: languageTags[locale],
      },
      ...(needsPerson
        ? [{
            '@type': 'Person',
            '@id': `${SITE_URL}/#chiaki`,
            name: '涼風千秋',
            alternateName: ['千秋', 'Chiaki Suzukaze', 'Suzukaze Chiaki'],
            url: `${SITE_URL}/profile`,
            mainEntityOfPage: `${SITE_URL}/profile`,
            sameAs: [
              'https://www.plurk.com/chiakich',
              'https://instagram.com/akisakuya',
              'https://github.com/chiakich',
            ],
          }]
        : []),
      pageNode,
      ...(breadcrumbItems.length
        ? [{
            '@type': 'BreadcrumbList',
            '@id': `${canonicalUrl}#breadcrumb`,
            itemListElement: breadcrumbItems.map((crumb, index) => ({
              '@type': 'ListItem',
              position: index + 1,
              name: crumb.name,
              item: crumb.url,
            })),
          }]
        : []),
    ],
  }

  return (
    <Head>
      <title key="title">{title}</title>
      <meta key="description" name="description" content={description} />
      <link key="canonical" rel="canonical" href={canonicalUrl} />
      {isLocalized ? (
        <>
          {(['tw', 'ja', 'en'] as Locale[]).map((alternateLocale) => (
            <link
              key={`alternate-${alternateLocale}`}
              rel="alternate"
              hrefLang={languageTags[alternateLocale]}
              href={`${SITE_URL}${localizedPath(pagePath, alternateLocale)}`}
            />
          ))}
          <link key="alternate-default" rel="alternate" hrefLang="x-default" href={`${SITE_URL}${pagePath === '/' ? '' : pagePath}`} />
        </>
      ) : override?.canonical ? null : (
        <link key="alternate-self" rel="alternate" hrefLang={inLanguage} href={canonicalUrl} />
      )}
      <meta key="og:type" property="og:type" content={ogType} />
      <meta key="og:url" property="og:url" content={canonicalUrl} />
      <meta key="og:title" property="og:title" content={title} />
      <meta
        key="og:description"
        property="og:description"
        content={description}
      />
      <meta key="og:image" property="og:image" content={imageUrl} />
      <meta key="og:image:width" property="og:image:width" content="1200" />
      <meta key="og:image:height" property="og:image:height" content="630" />
      <meta key="og:image:alt" property="og:image:alt" content={title} />
      <meta key="og:site_name" property="og:site_name" content={SITE_NAME} />
      <meta key="og:locale" property="og:locale" content={locale === 'ja' ? 'ja_JP' : locale === 'en' ? 'en_US' : 'zh_TW'} />
      {isArticle && override?.article && (
        <>
          <meta key="article:published_time" property="article:published_time" content={override.article.publishedTime} />
          {override.article.modifiedTime && (
            <meta key="article:modified_time" property="article:modified_time" content={override.article.modifiedTime} />
          )}
          {override.article.tags?.map((tag) => (
            <meta key={`article:tag:${tag}`} property="article:tag" content={tag} />
          ))}
        </>
      )}
      <meta key="twitter:card" name="twitter:card" content="summary_large_image" />
      <meta key="twitter:url" name="twitter:url" content={canonicalUrl} />
      <meta key="twitter:title" name="twitter:title" content={title} />
      <meta
        key="twitter:description"
        name="twitter:description"
        content={description}
      />
      <meta key="twitter:image" name="twitter:image" content={imageUrl} />
      <meta
        key="twitter:image:alt"
        name="twitter:image:alt"
        content={title}
      />
      <script
        key="structured-data"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
      />
    </Head>
  )
}

export default PageMeta
